export const RECOMMENDED_STAPLES = {
	pantry: [
		{ name: 'olive oil', checked: true },
		{ name: 'salt', checked: true },
		{ name: 'black pepper', checked: true },
		{ name: 'all-purpose flour', checked: true },
		{ name: 'sugar', checked: true },
		{ name: 'rice', checked: true },
		{ name: 'pasta', checked: true },
		{ name: 'soy sauce', checked: false },
		{ name: 'vegetable oil', checked: false },
		{ name: 'canned tomatoes', checked: false },
		{ name: 'chicken stock', checked: false },
		{ name: 'honey', checked: false },
		{ name: 'baking powder', checked: false },
		{ name: 'vanilla extract', checked: false },
		{ name: 'rice vinegar', checked: false },
		{ name: 'sesame oil', checked: false },
	],
	fridge: [
		{ name: 'eggs', checked: true },
		{ name: 'butter', checked: true },
		{ name: 'milk', checked: true },
		{ name: 'onions', checked: true },
		{ name: 'garlic', checked: true },
		{ name: 'carrots', checked: false },
		{ name: 'parmesan cheese', checked: false },
		{ name: 'yogurt', checked: false },
		{ name: 'bell peppers', checked: false },
		{ name: 'ginger', checked: false },
		{ name: 'scallions', checked: false },
		{ name: 'heavy cream', checked: false },
	],
	freezer: [
		{ name: 'chicken breast', checked: true },
		{ name: 'ground beef', checked: false },
		{ name: 'bacon', checked: false },
		{ name: 'frozen peas', checked: false },
		{ name: 'mixed vegetables', checked: false },
	],
} as const

export type StapleLocation = keyof typeof RECOMMENDED_STAPLES
