import { OpenImgContextProvider } from 'openimg/react'
import {
	data,
	Link,
	Links,
	Meta,
	NavLink,
	Outlet,
	Scripts,
	ScrollRestoration,
	useLoaderData,
	useLocation,
} from 'react-router'
import { type Route } from './+types/root.ts'
import appleTouchIconAssetUrl from './assets/favicons/apple-touch-icon.png'
import dmSansFontUrl from './assets/fonts/dm-sans-latin.woff2?url'
import youngSerifFontUrl from './assets/fonts/young-serif-latin.woff2?url'
import faviconAssetUrl from './assets/favicons/favicon.svg'
import { BottomNav } from './components/bottom-nav.tsx'
import { GeneralErrorBoundary } from './components/error-boundary.tsx'
import { HouseholdActivityNotifier } from './components/household-activity-notifier.tsx'
import { NativeShellBridge } from './components/native-shell-bridge.tsx'
import { NavTiming } from './components/nav-timing.tsx'
import { OfflineIndicator } from './components/offline-indicator.tsx'
import { ProExpiryNudge } from './components/pro-expiry-nudge.tsx'
import { ServiceWorkerDataSync } from './components/service-worker-data-sync.tsx'
import { ServiceWorkerUpdate } from './components/service-worker-update.tsx'
import { useToast } from './components/toaster.tsx'
import { Button } from './components/ui/button.tsx'
import { Toaster } from './components/ui/sonner.tsx'
import { UserDropdown } from './components/user-dropdown.tsx'
import { useOptionalTheme, useTheme } from './routes/resources/theme-switch.tsx'
import tailwindStyleSheetUrl from './styles/tailwind.css?url'
import {
	getUserId,
	logout,
	refreshSessionIfNeeded,
} from './utils/auth.server.ts'
import { ClientHintCheck, getHints } from './utils/client-hints.tsx'
import { prisma } from './utils/db.server.ts'
import { getEnv } from './utils/env.server.ts'
import { pipeHeaders } from './utils/headers.server.ts'
import { combineHeaders, getDomainUrl, getImgSrc } from './utils/misc.tsx'
import { isNativeShell } from './utils/native-shell.server.ts'
import { useNavDirection } from './utils/nav-direction.ts'
import { useNonce } from './utils/nonce-provider.ts'
import { getPostHogHost } from './utils/posthog-config.ts'
import {
	PostHogIdentify,
	PostHogPageview,
	PostHogPwaLifecycle,
} from './utils/posthog-provider.tsx'
import { iosStartupImages, launchThemes } from './utils/pwa-launch.ts'
import { getUserTier, type TierInfo } from './utils/subscription.server.ts'
import { type Theme, getTheme } from './utils/theme.server.ts'
import { makeTimings, time } from './utils/timing.server.ts'
import { hasPendingToastCookie } from './utils/toast-pending.ts'
import { getToast } from './utils/toast.server.ts'
import { useOptionalUser } from './utils/user.ts'

export const links: Route.LinksFunction = () => {
	return [
		// Self-hosted fonts (app/styles/fonts.css). The two faces above the fold
		// are preloaded; fonts need crossOrigin even on the same origin.
		{
			rel: 'preload',
			href: dmSansFontUrl,
			as: 'font',
			type: 'font/woff2',
			crossOrigin: 'anonymous',
		} as const,
		{
			rel: 'preload',
			href: youngSerifFontUrl,
			as: 'font',
			type: 'font/woff2',
			crossOrigin: 'anonymous',
		} as const,
		{
			rel: 'icon',
			href: '/favicon.ico',
			sizes: '48x48',
		},
		{ rel: 'icon', type: 'image/svg+xml', href: faviconAssetUrl },
		{ rel: 'apple-touch-icon', href: appleTouchIconAssetUrl },
		{
			rel: 'manifest',
			href: '/site.webmanifest',
			crossOrigin: 'use-credentials',
		} as const, // necessary to make typescript happy
		// iOS PWA startup images (generated by other/generate-splash-screens.ts)
		...iosStartupImages.map(({ href, media }) => ({
			rel: 'apple-touch-startup-image' as const,
			href,
			media,
		})),
		{ rel: 'stylesheet', href: tailwindStyleSheetUrl },
	].filter(Boolean)
}

export const meta: Route.MetaFunction = ({ loaderData }) => {
	const origin = loaderData?.requestInfo.origin ?? ''
	const description =
		'Save Recipes, plan Meals, and make one useful Shopping list.'
	return [
		{ title: loaderData ? 'Quartermaster' : 'Error | Quartermaster' },
		{ name: 'description', content: description },
		{ property: 'og:site_name', content: 'Quartermaster' },
		{ property: 'og:title', content: 'Quartermaster' },
		{
			property: 'og:description',
			content: description,
		},
		{ property: 'og:image', content: `${origin}/og-image.png` },
		{ property: 'og:image:width', content: '1200' },
		{ property: 'og:image:height', content: '630' },
		{ property: 'og:type', content: 'website' },
		{ property: 'og:locale', content: 'en_US' },
		{ name: 'twitter:card', content: 'summary_large_image' },
	]
}

const DEFAULT_TIER_INFO: TierInfo = {
	tier: 'free',
	isProActive: false,
	isTrialing: false,
	trialEndsAt: null,
	subscriptionExpiresAt: null,
	hasStripeSubscription: false,
	proExpiresAt: null,
	daysUntilExpiry: null,
	wasProPreviously: false,
}

export async function loader({ request }: Route.LoaderArgs) {
	const timings = makeTimings('root loader')
	const userId = await time(() => getUserId(request), {
		timings,
		type: 'getUserId',
		desc: 'getUserId in root',
	})

	// These lookups are independent of each other — run them concurrently.
	// This loader runs on every forced revalidation, so its latency is
	// navigation latency. getUserId has already logged out an expired session,
	// so the refresh only ever extends a live one.
	const [user, tierInfo, member, toastResult, sessionCookie] =
		await Promise.all([
			userId
				? time(
						() =>
							prisma.user.findUnique({
								select: {
									id: true,
									name: true,
									username: true,
									roles: {
										select: {
											name: true,
											permissions: {
												select: { entity: true, action: true, access: true },
											},
										},
									},
								},
								where: { id: userId },
							}),
						{ timings, type: 'find user', desc: 'find user in root' },
					)
				: null,
			userId ? getUserTier(userId) : DEFAULT_TIER_INFO,
			userId
				? prisma.householdMember.findFirst({
						where: { userId },
						select: {
							household: { select: { id: true, name: true } },
						},
					})
				: null,
			getToast(request),
			userId ? refreshSessionIfNeeded(request) : null,
		])
	if (userId && !user) {
		console.info('something weird happened')
		// something weird happened... The user is authenticated but we can't find
		// them in the database. Maybe they were deleted? Let's log them out.
		await logout({ request, redirectTo: '/' })
	}

	const householdId = member?.household.id ?? null
	const householdName = member?.household.name ?? null
	const { toast, headers: toastHeaders } = toastResult
	return data(
		{
			user,
			tierInfo,
			householdId,
			householdName,
			requestInfo: {
				hints: getHints(request),
				origin: getDomainUrl(request),
				path: new URL(request.url).pathname,
				isNativeShell: isNativeShell(request),
				userPrefs: {
					theme: getTheme(request),
				},
			},
			ENV: getEnv(),
			toast,
		},
		{
			headers: combineHeaders(
				{ 'Server-Timing': timings.toString() },
				toastHeaders,
				sessionCookie ? { 'set-cookie': sessionCookie } : null,
			),
		},
	)
}

/**
 * When to re-run the root loader. It provides mostly-static data (user, theme,
 * ENV) and notification count (tracked client-side via SSE).
 *
 * With single fetch (React Router 8.3), the router passes
 * `defaultShouldRevalidate: true` to every match on any navigation that is not
 * after a failed action, so deferring to it re-runs root on page-to-page
 * navigations too, back and forward included. Links that should skip root opt
 * out at the call site with `defaultShouldRevalidate={false}` (the bottom tab
 * bar does, between tabs).
 *
 * Revalidate when:
 * - A flash toast is pending (the `en_toast_pending` marker cookie set by
 *   `createToastHeaders`): the next root-loader run renders and clears it.
 *   This is an explicit signal, not an inference from URL shape — a
 *   `redirectWithToast` that keeps the pathname and only changes the search
 *   (e.g. /upgrade?session_id=… → /upgrade) still delivers its toast.
 * - The router says so (`defaultShouldRevalidate`): page-to-page and back or
 *   forward navigations (see above), same-URL revalidation, forced
 *   revalidation (Set-Cookie redirects replayed as X-Remix-Revalidate,
 *   useRevalidator), and successful form submissions.
 *
 * Skip when:
 * - Search params change on the same page (filters, pagination) — root data
 *   doesn't depend on them.
 * - The router says so: a link that opts out, and after a failed (4xx)
 *   action, where the router deliberately skips revalidation — the old
 *   unconditional `if (formAction) return true` overrode that and re-ran the
 *   root queries on every validation error.
 */
export function shouldRevalidate({
	defaultShouldRevalidate,
	currentUrl,
	nextUrl,
}: {
	defaultShouldRevalidate: boolean
	currentUrl: URL
	nextUrl: URL
}) {
	// A toast is waiting — never skip, whatever shape the navigation takes.
	if (hasPendingToastCookie()) return true

	// Search params changed on the same page (filters, pagination) — root data
	// doesn't depend on them, so skip even though the router defaults to true.
	// A pending toast can't be stranded here: it would have hit the marker
	// check above.
	if (
		currentUrl.pathname === nextUrl.pathname &&
		currentUrl.search !== nextUrl.search
	) {
		return false
	}

	// Otherwise defer to the router: false after failed (4xx) actions and when a
	// link opts out, true otherwise (see above), including same-URL
	// revalidation, forced revalidation and successful submissions.
	return defaultShouldRevalidate
}

export const headers: Route.HeadersFunction = pipeHeaders

function Document({
	children,
	nonce,
	theme = 'light',
	env = {},
	origin,
	path,
	isNativeShell = false,
}: {
	children: React.ReactNode
	nonce: string
	theme?: Theme
	env?: Record<string, string | undefined>
	origin?: string
	path?: string
	isNativeShell?: boolean
}) {
	const allowIndexing = ENV.ALLOW_INDEXING !== 'false'
	const launchTheme = launchThemes[theme]
	const posthogOrigin = env.POSTHOG_API_KEY
		? new URL(getPostHogHost(env.POSTHOG_HOST)).origin
		: null
	return (
		<html
			lang="en"
			className={`${theme} h-full overflow-x-hidden`}
			// The iOS app draws the page under the status bar; tailwind.css keys
			// the safe-area padding off this attribute.
			data-native-shell={isNativeShell ? '' : undefined}
		>
			<head>
				<meta charSet="utf-8" />
				<meta name="color-scheme" content="light dark" />
				<meta
					name="theme-color"
					content={launchThemes.light.canvas}
					media="(prefers-color-scheme: light)"
				/>
				<meta
					name="theme-color"
					content={launchThemes.dark.canvas}
					media="(prefers-color-scheme: dark)"
				/>
				<style
					nonce={nonce}
					data-pwa-launch-theme={theme}
					dangerouslySetInnerHTML={{
						__html: `:root{color-scheme:${theme}}html,body{background:${launchTheme.canvas};color:${launchTheme.foreground}}`,
					}}
				/>
				<ClientHintCheck nonce={nonce} />
				<Meta />
				{posthogOrigin ? (
					<link rel="preconnect" href={posthogOrigin} crossOrigin="anonymous" />
				) : null}
				<meta
					name="viewport"
					content={
						isNativeShell
							? 'width=device-width,initial-scale=1,viewport-fit=cover'
							: 'width=device-width,initial-scale=1'
					}
				/>
				<meta name="mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="default" />
				<meta name="apple-mobile-web-app-title" content="Quartermaster" />
				{allowIndexing ? null : (
					<meta name="robots" content="noindex, nofollow" />
				)}
				{origin && path ? (
					<link rel="canonical" href={`${origin}${path}`} />
				) : null}
				<Links />
			</head>
			<body className="bg-background text-foreground paper-grain">
				<a
					href="#main-content"
					className="focus:bg-card focus:shadow-warm-lg sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:rounded-md focus:px-4 focus:py-2 focus:text-sm focus:font-medium"
				>
					Skip to content
				</a>
				{children}
				<script
					nonce={nonce}
					dangerouslySetInnerHTML={{
						__html: `window.ENV = ${JSON.stringify(env)}`,
					}}
				/>
				<ScrollRestoration nonce={nonce} />
				<Scripts nonce={nonce} />
			</body>
		</html>
	)
}

export function Layout({ children }: { children: React.ReactNode }) {
	// if there was an error running the loader, data could be missing
	const data = useLoaderData<typeof loader | null>()
	const nonce = useNonce()
	const theme = useOptionalTheme()
	return (
		<Document
			nonce={nonce}
			theme={theme}
			env={data?.ENV}
			origin={data?.requestInfo.origin}
			path={data?.requestInfo.path}
			isNativeShell={data?.requestInfo.isNativeShell}
		>
			{children}
		</Document>
	)
}

function App() {
	const data = useLoaderData<typeof loader>()
	const user = useOptionalUser()
	const theme = useTheme()
	const isPro = data.tierInfo.isProActive
	const { pathname } = useLocation()
	const isNativeShell = data.requestInfo.isNativeShell
	// The homepage re-themes the chrome around it to espresso in either theme.
	const chrome = pathname === '/' ? 'espresso' : undefined
	useToast(data.toast)
	useNavDirection()

	return (
		<NavTiming>
			<PostHogIdentify
				user={
					user
						? { id: user.id, name: user.name, username: user.username }
						: null
				}
				householdId={data.householdId}
			/>
			<PostHogPageview />
			<PostHogPwaLifecycle />
			<ServiceWorkerDataSync
				userId={user?.id ?? null}
				householdId={data.householdId}
			/>
			<ServiceWorkerUpdate />
			{isNativeShell ? (
				// The status bar sits on the chrome, so espresso needs light text.
				<NativeShellBridge theme={chrome === 'espresso' ? 'dark' : theme} />
			) : null}
			<OpenImgContextProvider
				optimizerEndpoint="/resources/images"
				getSrc={getImgSrc}
			>
				<div
					className="flex min-h-screen flex-col justify-between"
					data-chrome={chrome}
				>
					{isNativeShell ? (
						// Content scrolls under the status bar behind the same frosted
						// background as the bottom tab bar.
						<div
							aria-hidden="true"
							data-status-bar-backdrop=""
							className="bg-card/95 pointer-events-none fixed inset-x-0 top-0 z-50 h-[env(safe-area-inset-top)] backdrop-blur-sm print:hidden"
						/>
					) : null}
					<header
						data-site-header=""
						className="bg-card/80 border-border/50 z-40 border-b backdrop-blur-sm md:sticky md:top-0"
					>
						<nav
							aria-label="Main"
							className="container flex flex-wrap items-center justify-between gap-4 py-3 sm:flex-nowrap md:gap-8"
						>
							<Logo />
							<div className="ml-auto flex items-center gap-4 md:gap-10">
								{user ? (
									<>
										<div className="hidden items-center gap-2 md:flex">
											<NavLink
												to="/recipes"
												prefetch="intent"
												className={({ isActive }) =>
													isActive
														? 'text-primary rounded-full px-4 py-1.5 text-sm font-medium transition-all duration-200'
														: 'text-muted-foreground hover:text-primary rounded-full px-4 py-1.5 text-sm transition-all duration-200'
												}
											>
												Recipes
											</NavLink>
											<NavLink
												to="/inventory"
												prefetch="intent"
												className={({ isActive }) =>
													isActive
														? 'text-primary rounded-full px-4 py-1.5 text-sm font-medium transition-all duration-200'
														: 'text-muted-foreground hover:text-primary rounded-full px-4 py-1.5 text-sm transition-all duration-200'
												}
											>
												Staples
											</NavLink>
											<NavLink
												to="/plan"
												prefetch="intent"
												className={({ isActive }) =>
													isActive
														? 'text-primary rounded-full px-4 py-1.5 text-sm font-medium transition-all duration-200'
														: 'text-muted-foreground hover:text-primary rounded-full px-4 py-1.5 text-sm transition-all duration-200'
												}
											>
												Plan
											</NavLink>
											<NavLink
												to="/shopping"
												prefetch="intent"
												className={({ isActive }) =>
													isActive
														? 'text-primary rounded-full px-4 py-1.5 text-sm font-medium transition-all duration-200'
														: 'text-muted-foreground hover:text-primary rounded-full px-4 py-1.5 text-sm transition-all duration-200'
												}
											>
												Shopping
											</NavLink>
										</div>
										<UserDropdown />
									</>
								) : (
									<HeaderAuthButton />
								)}
							</div>
						</nav>
					</header>

					<main id="main-content" className="flex flex-1 flex-col">
						<Outlet />
					</main>
				</div>
				<BottomNav />
				<Toaster
					closeButton
					position="top-center"
					theme={theme}
					// Sonner's default offsets, pushed below the status bar in the iOS
					// app. The inset is 0 everywhere else.
					offset={{ top: 'calc(24px + env(safe-area-inset-top))' }}
					mobileOffset={{ top: 'calc(16px + env(safe-area-inset-top))' }}
				/>
				<OfflineIndicator />
				{user && isPro ? <HouseholdActivityNotifier /> : null}
				{user ? <ProExpiryNudge /> : null}
			</OpenImgContextProvider>
		</NavTiming>
	)
}

function Logo() {
	return (
		<Link to="/" className="group flex items-center gap-2">
			<span className="text-foreground font-sans text-xl font-medium tracking-tight">
				Quartermaster
			</span>
		</Link>
	)
}

function HeaderAuthButton() {
	const { pathname } = useLocation()
	const isLogin = pathname === '/login'
	return (
		<Button asChild variant="default" size="lg">
			<Link to={isLogin ? '/signup' : '/login'}>
				{isLogin ? 'Sign Up' : 'Log In'}
			</Link>
		</Button>
	)
}

function AppWithProviders() {
	return <App />
}

export default AppWithProviders

// this is a last resort error boundary. There's not much useful information we
// can offer at this level.
export const ErrorBoundary = GeneralErrorBoundary
